  # Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frisp Games
email: info@frispgames.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: frispgames
github_username:  frispgames
#url: "http://www.frispgames.com" # the base hostname & protocol for your site
url: "http://localhost:4000"
# Build settings
markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
permalink:       /:title/

disqus: true
disqus_shortname: 'kiwiprogrammer'

sass:
  sass_dir: _sass
  style: compressed

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: default
